declare module 'maplibre-gl-measures';
declare module 'cors';
declare module 'axios';
declare module '@maplibre/maplibre-gl-geocoder';
declare module 'xml2js';
declare module 'cookie';
declare module 'xlsx-style';
declare module 'swagger-ui-react';
declare module 'swagger-ui-express';